version: '3.9'

services:
  app:
    build:
      context: '.'
      dockerfile: ${DOCKERFILE}
      args:
        APP_ENV: ${APP_ENV}
        APP_GROUP: ${APP_GROUP}
        APP_PATH: ${APP_PATH}
        APP_USER: ${APP_USER}
        SERVER_NAME: ${SERVER_NAME}
    image: ${DOCKER_IMAGE}
    restart: unless-stopped
    container_name: ${DOCKER_NAME}-app
    environment:
      TZ: Europe/London
    working_dir: ${APP_PATH}
    volumes:
      - ${LOCAL_PATH}/storage:${APP_PATH}/storage
    ports:
      - ${HOST_PORT}:80
    networks:
      backend:
        aliases:
          - ${DOCKER_NAME}-app
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "-f", "localhost"]
      interval: "60s"
      timeout: "3s"
      start_period: "30s"
      retries: 3

networks:
  backend:
    name: ${DOCKER_NAME}-network
    driver: ${DOCKER_NETWORK_DRIVER}
